### ISSUE TITLE
combobox: support type=search placeholderMode

### ISSUE THREAD

**Issue by yiminghe** [kissyteam/kissy#655]
http://dev.kissyui.com/kissy/src/combobox/demo/other/native.html

``` javascript
KISSY.use("combobox", function (S, ComboBox) {
  new ComboBox({
                render: "#newNew",
                hasTrigger: false,
                placeholder: 'input number!',
                width: 400
  });
});
```

if u want to make placeholder invisible after focus like 1.4.x, add the following css:

``` css
.ks-combobox-focused .ks-combobox-placeholder {
   visibility:hidden;
}
```
